<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Tag;
use App\Models\VendorProfile;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class VendorController extends Controller
{
    /**
     * 1. Dashboard View Loader
     * Loads the unified storefront and article authoring workspace panels.
     */
    public function index()
    {
        // Fetch or instantiate a blank profile container backing data for this vendor
        $profile = VendorProfile::firstOrCreate(['user_id' => Auth::id()]);

        // Fetch all categories generated by the admin so checkboxes populate
        $allTags = Tag::orderBy('name', 'asc')->get();

        return view('vendor.dashboard', compact('profile', 'allTags'));
    }

    /**
     * 2. Save/Update Profile Configurations
     * Validates metadata, saves storefront image assets, and syncs pivot tables.
     */
    public function updateProfile(Request $request)
    {
        $request->validate([
            'description'  => 'required|string',
            'opening_time' => 'required',
            'closing_time' => 'required',
            'picture'      => 'nullable|image|mimes:jpeg,png,jpg|max:2048', // 2MB Max limit
            'tags'         => 'nullable|array',
        ]);

        // Fetch or instantiate the profile shell
        $profile = VendorProfile::firstOrCreate(['user_id' => Auth::id()]);

        // Handle Image upload if a new file stream was provided
        if ($request->hasFile('picture')) {
            
            // Clean up: Delete old profile pictures from local disk if they exist
            if ($profile->picture) {
                Storage::disk('public')->delete($profile->picture);
            }

            // Store the new file in the "profiles" directory on the public disk
            $path = $request->file('picture')->store('profiles', 'public');
            
            // Save the relative path into the database column
            $profile->picture = $path;
        }

        // Update core metadata attributes
        $profile->description  = $request->description;
        $profile->opening_time = $request->opening_time;
        $profile->closing_time = $request->closing_time;
        $profile->save();

        // Synchronize many-to-many business category checkboxes in pivot table
        $profile->tags()->sync($request->tags ?? []);

        return back()->with('success', 'Core storefront configuration profiles successfully synchronized!');
    }

    /**
     * 3. Global Customer Registry Link
     * Fulfills administrative operational read-access to complete system account profiles.
     */
    public function userRegistry()
    {
        // Pull down complete user accounts tracking profiles with their attached system permissions
        $users = User::with('roles')->orderBy('id', 'desc')->paginate(10);

        return view('vendor.users-index', compact('users'));
    }
}