<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Tag;
use App\Models\VendorProfile; 
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class VendorController extends Controller
{
    public function index()
    {
        // Fetch the current vendor's existing profile details
        // If a profile doesn't exist for this user, automatically instantiate a blank record
        $profile = VendorProfile::firstOrCreate(['user_id' => Auth::id()]);

        // Fetch all global tags generated by the admin so the vendor can select them
        $allTags = Tag::orderBy('name', 'asc')->get();

        return view('vendor.dashboard', compact('profile', 'allTags'));
    }
}
